// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/pb.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	pb/pb.proto

It has these top-level messages:
	CS_Login
	CS_SendMsg
	SC_Account
	SC_Msg
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 登录
type CS_Login struct {
	User             *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Pass             *string `protobuf:"bytes,2,req,name=pass" json:"pass,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CS_Login) Reset()                    { *m = CS_Login{} }
func (m *CS_Login) String() string            { return proto.CompactTextString(m) }
func (*CS_Login) ProtoMessage()               {}
func (*CS_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CS_Login) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *CS_Login) GetPass() string {
	if m != nil && m.Pass != nil {
		return *m.Pass
	}
	return ""
}

// 消息
type CS_SendMsg struct {
	Msg              *string `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CS_SendMsg) Reset()                    { *m = CS_SendMsg{} }
func (m *CS_SendMsg) String() string            { return proto.CompactTextString(m) }
func (*CS_SendMsg) ProtoMessage()               {}
func (*CS_SendMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CS_SendMsg) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

// 玩家消息
type SC_Account struct {
	Id               *uint64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Nick             *string `protobuf:"bytes,2,req,name=nick" json:"nick,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SC_Account) Reset()                    { *m = SC_Account{} }
func (m *SC_Account) String() string            { return proto.CompactTextString(m) }
func (*SC_Account) ProtoMessage()               {}
func (*SC_Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SC_Account) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *SC_Account) GetNick() string {
	if m != nil && m.Nick != nil {
		return *m.Nick
	}
	return ""
}

// 消息
type SC_Msg struct {
	Msg              *string `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SC_Msg) Reset()                    { *m = SC_Msg{} }
func (m *SC_Msg) String() string            { return proto.CompactTextString(m) }
func (*SC_Msg) ProtoMessage()               {}
func (*SC_Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SC_Msg) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*CS_Login)(nil), "msg.CS_Login")
	proto.RegisterType((*CS_SendMsg)(nil), "msg.CS_SendMsg")
	proto.RegisterType((*SC_Account)(nil), "msg.SC_Account")
	proto.RegisterType((*SC_Msg)(nil), "msg.SC_Msg")
}

func init() { proto.RegisterFile("pb/pb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x48, 0xd2, 0x2f,
	0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x32, 0xe2, 0xe2,
	0x70, 0x0e, 0x8e, 0xf7, 0xc9, 0x4f, 0xcf, 0xcc, 0x13, 0x12, 0xe2, 0x62, 0x29, 0x2d, 0x4e, 0x2d,
	0x92, 0x60, 0x54, 0x60, 0xd2, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x05, 0x89, 0xc5, 0xc5, 0x12,
	0x4c, 0x10, 0x31, 0x10, 0x5b, 0x49, 0x8e, 0x8b, 0xcb, 0x39, 0x38, 0x3e, 0x38, 0x35, 0x2f, 0xc5,
	0xb7, 0x38, 0x5d, 0x48, 0x80, 0x0b, 0x64, 0x10, 0x54, 0x13, 0xd8, 0x4c, 0x03, 0x2e, 0xae, 0x60,
	0xe7, 0x78, 0xc7, 0xe4, 0xe4, 0xfc, 0xd2, 0xbc, 0x12, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0xb0,
	0x34, 0x4b, 0x10, 0x53, 0x66, 0x0a, 0xc8, 0xc4, 0xbc, 0xcc, 0xe4, 0x6c, 0x98, 0x89, 0x20, 0xb6,
	0x92, 0x14, 0x17, 0x5b, 0xb0, 0x73, 0x3c, 0x56, 0xd3, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe8,
	0x14, 0x50, 0xfd, 0xb4, 0x00, 0x00, 0x00,
}
